### ISSUE TITLE
IntelliSense is Broken

### ISSUE THREAD

**Issue by InteXX** [VBAndCs/Vazor#5]
It seems something has caused IntelliSense to stop working throughout the project. Restarting VS 2020 doesn't have any effect.

I'm not sure if it's related, but when I manually type a member that doesn't exist:

```
Dim x As String
x.Find
```

... I get this exception in the IDE:

```
System.TypeInitializationException : The type initializer for 'vbxmlCompProv.Microsoft.CodeAnalysis.VisualBasic.Completion.Providers.AbstractVbXmlCompletionProvider' threw an exception. ---> System.NullReferenceException : Object reference not set to an instance of an object.
   at vbxmlCompProv.Microsoft.CodeAnalysis.VisualBasic.Completion.Providers.AbstractVbXmlCompletionProvider.LoadHtmlSchema()
   at vbxmlCompProv.Microsoft.CodeAnalysis.VisualBasic.Completion.Providers.AbstractVbXmlCompletionProvider..cctor()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target,Object[] arguments,Signature sig,Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)
   at Microsoft.VisualStudio.Composition.ReflectionHelpers.Instantiate(MethodBase ctorOrFactoryMethod,Object[] arguments)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass63_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass52_3.<GetExports>b__5()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass80_1`2.<GetExports>b__2()
   at System.Lazy`1.CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.CreateRoleProviders(ImmutableHashSet`1 roles)
   at Roslyn.Utilities.IDictionaryExtensions.GetOrAdd[K,V](IDictionary`2 dictionary,K key,Func`2 function)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetProviders(ImmutableHashSet`1 roles)
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetFilteredProviders(Project project,ImmutableHashSet`1 roles,CompletionTrigger trigger,OptionSet options)
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsWithAvailabilityOfExpandedItemsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetCompletionsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CreateSpellCheckCodeIssueAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.CheckNodeAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.SpellCheck.AbstractSpellCheckCodeFixProvider`1.RegisterCodeFixesAsync[TSimpleName](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

**Comment by VBAndCs** [comment]
It workd only within the `<vbxml></vbxml>` and `<zml></zml>` tags, not to mess with other xml literals.

**Comment by InteXX** [comment]
IntelliSense is missing throughout the project, even inside standard classes:

```
Dim x As String = "UPPER"
Dim y As String = x.ToLower ' No IntelliSense here
```

**Comment by InteXX** [comment]
Also: see my edits to the original issue.

**Comment by VBAndCs** [comment]
Try to unstall VazorEx to see if it is the cause of the problem

**Comment by InteXX** [comment]
Uninstalled VazorEx and IntelliSense is back.

Workaround: now that I have a project, I don't need the template. I'll reinstall VazorEx to get copies of the two Item templates you've created, and then I'll uninstall again.

**Comment by VBAndCs** [comment]
Locl at `Libraries\Documents`: can you find these two files:
commonHTML5Types.xsd
html_5.xsd

I copy them from VS dir because the long path causes errors. Maybe VS2022 professional has a different path on ypur Pc. If you don't see these two file, search for them in VS2022 dir and copy them manually  to  `Libraries\Documents` dir.

**Comment by InteXX** [comment]
Where is `Libraries\Documents`?

**Comment by VBAndCs** [comment]
C:\Users\[username]\Documents

**Comment by InteXX** [comment]
OK, copied from `C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Packages\Schemas\html`.

Reinstalled VazorEx, no IntelliSense (even in VB classes).

```
Dim x As String = "UPPER"
Dim y As String = x.ToLower ' No IntelliSense here
```

Same IDE exception as described above.

**Comment by InteXX** [comment]
I don't have to uninstall VazorEx to get IntelliSense back and to stop the IDE exception—I accomplished this by just disabling the extension.

Like I said, I've got what I need to proceed. For new projects, I'll just copy from these projects (MVC and RazorPages) as needed.

**Comment by VBAndCs** [comment]
The starge thing is that I have the same error in VS2019 (a fresh install), but not in VS2022 (old install). I think MS changes something in these two files that causes the bug. I didn't want to copy them to keep up with any updates, but seems this was a bad choice!

**Comment by VBAndCs** [comment]
Yes, I used the old 2 files and the provider works! MS did change something in these two files!
I will modify VazorEX to inculde the old 2 files, and until then you can use these attachhed files.
Thanks.
[xsd.zip](https://github.com/VBAndCs/Vazor/files/8312416/xsd.zip)

**Comment by VBAndCs** [comment]
@InteXX 
I updated VazorEx extebstion. Auto completion works fine now in both VS2019 and VS2022.
Thanks.
